### ISSUE TITLE
Timeout on blocking read when connecting with cosmos client

### ISSUE THREAD

**Issue by zzgzy** [bindeshv/CosmosScala#1]
Hello author, 
hope you are doing great! I am searched through the github and looks like you are the only one who is using `CosmosClientBuilder `to connect to cosmosDB in scala. Have you ever seen error like T`imeout on blocking read for 120000 MILLISECONDS on connecting with cosmos client` when running the spark app on cluster? This error happens to me all the time and I am using the most recent 4.13.0 JAVA SDK. Any advice or suggestions are really appreciated! Thank you! 

Or a link to your blog post would also be really helpful. Thank you!

**Comment by bindeshv** [comment]
I never ran this code on Spark. But could you check with the connection mode and try with Direct/Gateway and see if helps?

**Comment by zzgzy** [comment]
Thank you! Yes, I tried both but no luck. I am going to close this as it's not an issue.
